services:
  web:
    image: nginx:latest
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./routes:/var/www/routes
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./public:/var/www/public
      - ./database:/var/www/database
      - ./compose.dev.yaml:/var/www/compose.dev.yaml
      - ./compose.prod.yaml:/var/www/compose.prod.yaml
      - ./docker:/var/www/docker
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package-lock.json:/var/www/package-lock.json
      - ./package.json:/var/www/package.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env.example:/var/www/.env.example
      - ./.dockerignore:/var/www/.dockerignore
      - ./.editorconfig:/var/www/.editorconfig
      - ./artisan:/var/www/artisan
      - ./vendor:/var/www/vendor
      - app-node-modules:/var/www/node_modules
      - ./storage:/var/www/storage
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - laravel-development
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    image: laravel-php-fpm:dev
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    pull_policy: never
    env_file:
      - .env
    user: "root"
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./routes:/var/www/routes
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./public:/var/www/public
      - ./database:/var/www/database
      - ./compose.dev.yaml:/var/www/compose.dev.yaml
      - ./compose.prod.yaml:/var/www/compose.prod.yaml
      - ./docker:/var/www/docker
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package-lock.json:/var/www/package-lock.json
      - ./package.json:/var/www/package.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env.example:/var/www/.env.example
      - ./.dockerignore:/var/www/.dockerignore
      - ./.editorconfig:/var/www/.editorconfig
      - ./artisan:/var/www/artisan
      - ./vendor:/var/www/vendor
      - app-node-modules:/var/www/node_modules
      - ./storage:/var/www/storage
    networks:
      - laravel-development
    depends_on:
      postgres:
        condition: service_started

  workspace:
    image: laravel-workspace:dev
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    pull_policy: never
    ports:
      - '${VITE_PORT:-5173}:5173'
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./routes:/var/www/routes
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./public:/var/www/public
      - ./database:/var/www/database
      - ./compose.dev.yaml:/var/www/compose.dev.yaml
      - ./compose.prod.yaml:/var/www/compose.prod.yaml
      - ./docker:/var/www/docker
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package-lock.json:/var/www/package-lock.json
      - ./package.json:/var/www/package.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env.example:/var/www/.env.example
      - ./.dockerignore:/var/www/.dockerignore
      - ./.editorconfig:/var/www/.editorconfig
      - ./artisan:/var/www/artisan
      - ./vendor:/var/www/vendor
      - app-node-modules:/var/www/node_modules
      - ./storage:/var/www/storage
    networks:
      - laravel-development

  postgres:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - laravel-development

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laravel-development

  java-api:
    build:
      context: ./java-api
    ports:
      - "8082:8090"
    networks:
      - laravel-development

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8085:80"
    depends_on:
      - redis
    volumes:
      - /home/echo/PythonSSE:/code/app
    networks:
      - laravel-development
    environment:
      - REDIS_HOST=redis
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432

networks:
  laravel-development:

volumes:
  postgres-data-development:
  app-node-modules:
